/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.equifax.fabric.uk.purposing.companies.courtjudgment;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Summary extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Summary\",\"namespace\":\"com.equifax.fabric.uk.purposing.companies.courtjudgment\",\"fields\":[{\"name\":\"currentCcjCount\",\"type\":[\"null\",\"int\"],\"dataClassification\":\"3\"},{\"name\":\"latestCcjDate\",\"type\":[\"null\",\"string\"],\"dataClassification\":\"3\"},{\"name\":\"satisfiedCcjCount\",\"type\":[\"null\",\"int\"],\"dataClassification\":\"3\"},{\"name\":\"latestSatisfiedCcjDate\",\"type\":[\"null\",\"string\"],\"dataClassification\":\"3\"},{\"name\":\"locationCcjCount\",\"type\":[\"null\",\"int\"],\"dataClassification\":\"3\"},{\"name\":\"locationCcjPercentage\",\"type\":[\"null\",\"string\"],\"dataClassification\":\"3\"},{\"name\":\"locationBusinessLimit\",\"type\":[\"null\",\"int\"],\"dataClassification\":\"3\"},{\"name\":\"ccjIndicator\",\"type\":[\"null\",\"boolean\"],\"dataClassification\":\"3\"},{\"name\":\"ccjDate\",\"type\":[\"null\",\"string\"],\"dataClassification\":\"3\"},{\"name\":\"gazetteDate\",\"type\":[\"null\",\"string\"],\"dataClassification\":\"3\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Integer currentCcjCount;
  @Deprecated public java.lang.CharSequence latestCcjDate;
  @Deprecated public java.lang.Integer satisfiedCcjCount;
  @Deprecated public java.lang.CharSequence latestSatisfiedCcjDate;
  @Deprecated public java.lang.Integer locationCcjCount;
  @Deprecated public java.lang.CharSequence locationCcjPercentage;
  @Deprecated public java.lang.Integer locationBusinessLimit;
  @Deprecated public java.lang.Boolean ccjIndicator;
  @Deprecated public java.lang.CharSequence ccjDate;
  @Deprecated public java.lang.CharSequence gazetteDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Summary() {}

  /**
   * All-args constructor.
   */
  public Summary(java.lang.Integer currentCcjCount, java.lang.CharSequence latestCcjDate, java.lang.Integer satisfiedCcjCount, java.lang.CharSequence latestSatisfiedCcjDate, java.lang.Integer locationCcjCount, java.lang.CharSequence locationCcjPercentage, java.lang.Integer locationBusinessLimit, java.lang.Boolean ccjIndicator, java.lang.CharSequence ccjDate, java.lang.CharSequence gazetteDate) {
    this.currentCcjCount = currentCcjCount;
    this.latestCcjDate = latestCcjDate;
    this.satisfiedCcjCount = satisfiedCcjCount;
    this.latestSatisfiedCcjDate = latestSatisfiedCcjDate;
    this.locationCcjCount = locationCcjCount;
    this.locationCcjPercentage = locationCcjPercentage;
    this.locationBusinessLimit = locationBusinessLimit;
    this.ccjIndicator = ccjIndicator;
    this.ccjDate = ccjDate;
    this.gazetteDate = gazetteDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return currentCcjCount;
    case 1: return latestCcjDate;
    case 2: return satisfiedCcjCount;
    case 3: return latestSatisfiedCcjDate;
    case 4: return locationCcjCount;
    case 5: return locationCcjPercentage;
    case 6: return locationBusinessLimit;
    case 7: return ccjIndicator;
    case 8: return ccjDate;
    case 9: return gazetteDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: currentCcjCount = (java.lang.Integer)value$; break;
    case 1: latestCcjDate = (java.lang.CharSequence)value$; break;
    case 2: satisfiedCcjCount = (java.lang.Integer)value$; break;
    case 3: latestSatisfiedCcjDate = (java.lang.CharSequence)value$; break;
    case 4: locationCcjCount = (java.lang.Integer)value$; break;
    case 5: locationCcjPercentage = (java.lang.CharSequence)value$; break;
    case 6: locationBusinessLimit = (java.lang.Integer)value$; break;
    case 7: ccjIndicator = (java.lang.Boolean)value$; break;
    case 8: ccjDate = (java.lang.CharSequence)value$; break;
    case 9: gazetteDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'currentCcjCount' field.
   */
  public java.lang.Integer getCurrentCcjCount() {
    return currentCcjCount;
  }

  /**
   * Sets the value of the 'currentCcjCount' field.
   * @param value the value to set.
   */
  public void setCurrentCcjCount(java.lang.Integer value) {
    this.currentCcjCount = value;
  }

  /**
   * Gets the value of the 'latestCcjDate' field.
   */
  public java.lang.CharSequence getLatestCcjDate() {
    return latestCcjDate;
  }

  /**
   * Sets the value of the 'latestCcjDate' field.
   * @param value the value to set.
   */
  public void setLatestCcjDate(java.lang.CharSequence value) {
    this.latestCcjDate = value;
  }

  /**
   * Gets the value of the 'satisfiedCcjCount' field.
   */
  public java.lang.Integer getSatisfiedCcjCount() {
    return satisfiedCcjCount;
  }

  /**
   * Sets the value of the 'satisfiedCcjCount' field.
   * @param value the value to set.
   */
  public void setSatisfiedCcjCount(java.lang.Integer value) {
    this.satisfiedCcjCount = value;
  }

  /**
   * Gets the value of the 'latestSatisfiedCcjDate' field.
   */
  public java.lang.CharSequence getLatestSatisfiedCcjDate() {
    return latestSatisfiedCcjDate;
  }

  /**
   * Sets the value of the 'latestSatisfiedCcjDate' field.
   * @param value the value to set.
   */
  public void setLatestSatisfiedCcjDate(java.lang.CharSequence value) {
    this.latestSatisfiedCcjDate = value;
  }

  /**
   * Gets the value of the 'locationCcjCount' field.
   */
  public java.lang.Integer getLocationCcjCount() {
    return locationCcjCount;
  }

  /**
   * Sets the value of the 'locationCcjCount' field.
   * @param value the value to set.
   */
  public void setLocationCcjCount(java.lang.Integer value) {
    this.locationCcjCount = value;
  }

  /**
   * Gets the value of the 'locationCcjPercentage' field.
   */
  public java.lang.CharSequence getLocationCcjPercentage() {
    return locationCcjPercentage;
  }

  /**
   * Sets the value of the 'locationCcjPercentage' field.
   * @param value the value to set.
   */
  public void setLocationCcjPercentage(java.lang.CharSequence value) {
    this.locationCcjPercentage = value;
  }

  /**
   * Gets the value of the 'locationBusinessLimit' field.
   */
  public java.lang.Integer getLocationBusinessLimit() {
    return locationBusinessLimit;
  }

  /**
   * Sets the value of the 'locationBusinessLimit' field.
   * @param value the value to set.
   */
  public void setLocationBusinessLimit(java.lang.Integer value) {
    this.locationBusinessLimit = value;
  }

  /**
   * Gets the value of the 'ccjIndicator' field.
   */
  public java.lang.Boolean getCcjIndicator() {
    return ccjIndicator;
  }

  /**
   * Sets the value of the 'ccjIndicator' field.
   * @param value the value to set.
   */
  public void setCcjIndicator(java.lang.Boolean value) {
    this.ccjIndicator = value;
  }

  /**
   * Gets the value of the 'ccjDate' field.
   */
  public java.lang.CharSequence getCcjDate() {
    return ccjDate;
  }

  /**
   * Sets the value of the 'ccjDate' field.
   * @param value the value to set.
   */
  public void setCcjDate(java.lang.CharSequence value) {
    this.ccjDate = value;
  }

  /**
   * Gets the value of the 'gazetteDate' field.
   */
  public java.lang.CharSequence getGazetteDate() {
    return gazetteDate;
  }

  /**
   * Sets the value of the 'gazetteDate' field.
   * @param value the value to set.
   */
  public void setGazetteDate(java.lang.CharSequence value) {
    this.gazetteDate = value;
  }

  /** Creates a new Summary RecordBuilder */
  public static com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder newBuilder() {
    return new com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder();
  }
  
  /** Creates a new Summary RecordBuilder by copying an existing Builder */
  public static com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder newBuilder(com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder other) {
    return new com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder(other);
  }
  
  /** Creates a new Summary RecordBuilder by copying an existing Summary instance */
  public static com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder newBuilder(com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary other) {
    return new com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder(other);
  }
  
  /**
   * RecordBuilder for Summary instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Summary>
    implements org.apache.avro.data.RecordBuilder<Summary> {

    private java.lang.Integer currentCcjCount;
    private java.lang.CharSequence latestCcjDate;
    private java.lang.Integer satisfiedCcjCount;
    private java.lang.CharSequence latestSatisfiedCcjDate;
    private java.lang.Integer locationCcjCount;
    private java.lang.CharSequence locationCcjPercentage;
    private java.lang.Integer locationBusinessLimit;
    private java.lang.Boolean ccjIndicator;
    private java.lang.CharSequence ccjDate;
    private java.lang.CharSequence gazetteDate;

    /** Creates a new Builder */
    private Builder() {
      super(com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.currentCcjCount)) {
        this.currentCcjCount = data().deepCopy(fields()[0].schema(), other.currentCcjCount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latestCcjDate)) {
        this.latestCcjDate = data().deepCopy(fields()[1].schema(), other.latestCcjDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.satisfiedCcjCount)) {
        this.satisfiedCcjCount = data().deepCopy(fields()[2].schema(), other.satisfiedCcjCount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.latestSatisfiedCcjDate)) {
        this.latestSatisfiedCcjDate = data().deepCopy(fields()[3].schema(), other.latestSatisfiedCcjDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.locationCcjCount)) {
        this.locationCcjCount = data().deepCopy(fields()[4].schema(), other.locationCcjCount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locationCcjPercentage)) {
        this.locationCcjPercentage = data().deepCopy(fields()[5].schema(), other.locationCcjPercentage);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.locationBusinessLimit)) {
        this.locationBusinessLimit = data().deepCopy(fields()[6].schema(), other.locationBusinessLimit);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ccjIndicator)) {
        this.ccjIndicator = data().deepCopy(fields()[7].schema(), other.ccjIndicator);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ccjDate)) {
        this.ccjDate = data().deepCopy(fields()[8].schema(), other.ccjDate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.gazetteDate)) {
        this.gazetteDate = data().deepCopy(fields()[9].schema(), other.gazetteDate);
        fieldSetFlags()[9] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Summary instance */
    private Builder(com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary other) {
            super(com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.SCHEMA$);
      if (isValidValue(fields()[0], other.currentCcjCount)) {
        this.currentCcjCount = data().deepCopy(fields()[0].schema(), other.currentCcjCount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latestCcjDate)) {
        this.latestCcjDate = data().deepCopy(fields()[1].schema(), other.latestCcjDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.satisfiedCcjCount)) {
        this.satisfiedCcjCount = data().deepCopy(fields()[2].schema(), other.satisfiedCcjCount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.latestSatisfiedCcjDate)) {
        this.latestSatisfiedCcjDate = data().deepCopy(fields()[3].schema(), other.latestSatisfiedCcjDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.locationCcjCount)) {
        this.locationCcjCount = data().deepCopy(fields()[4].schema(), other.locationCcjCount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locationCcjPercentage)) {
        this.locationCcjPercentage = data().deepCopy(fields()[5].schema(), other.locationCcjPercentage);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.locationBusinessLimit)) {
        this.locationBusinessLimit = data().deepCopy(fields()[6].schema(), other.locationBusinessLimit);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ccjIndicator)) {
        this.ccjIndicator = data().deepCopy(fields()[7].schema(), other.ccjIndicator);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ccjDate)) {
        this.ccjDate = data().deepCopy(fields()[8].schema(), other.ccjDate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.gazetteDate)) {
        this.gazetteDate = data().deepCopy(fields()[9].schema(), other.gazetteDate);
        fieldSetFlags()[9] = true;
      }
    }

    /** Gets the value of the 'currentCcjCount' field */
    public java.lang.Integer getCurrentCcjCount() {
      return currentCcjCount;
    }
    
    /** Sets the value of the 'currentCcjCount' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setCurrentCcjCount(java.lang.Integer value) {
      validate(fields()[0], value);
      this.currentCcjCount = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'currentCcjCount' field has been set */
    public boolean hasCurrentCcjCount() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'currentCcjCount' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearCurrentCcjCount() {
      currentCcjCount = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'latestCcjDate' field */
    public java.lang.CharSequence getLatestCcjDate() {
      return latestCcjDate;
    }
    
    /** Sets the value of the 'latestCcjDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setLatestCcjDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.latestCcjDate = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'latestCcjDate' field has been set */
    public boolean hasLatestCcjDate() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'latestCcjDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearLatestCcjDate() {
      latestCcjDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'satisfiedCcjCount' field */
    public java.lang.Integer getSatisfiedCcjCount() {
      return satisfiedCcjCount;
    }
    
    /** Sets the value of the 'satisfiedCcjCount' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setSatisfiedCcjCount(java.lang.Integer value) {
      validate(fields()[2], value);
      this.satisfiedCcjCount = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'satisfiedCcjCount' field has been set */
    public boolean hasSatisfiedCcjCount() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'satisfiedCcjCount' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearSatisfiedCcjCount() {
      satisfiedCcjCount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'latestSatisfiedCcjDate' field */
    public java.lang.CharSequence getLatestSatisfiedCcjDate() {
      return latestSatisfiedCcjDate;
    }
    
    /** Sets the value of the 'latestSatisfiedCcjDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setLatestSatisfiedCcjDate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.latestSatisfiedCcjDate = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'latestSatisfiedCcjDate' field has been set */
    public boolean hasLatestSatisfiedCcjDate() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'latestSatisfiedCcjDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearLatestSatisfiedCcjDate() {
      latestSatisfiedCcjDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'locationCcjCount' field */
    public java.lang.Integer getLocationCcjCount() {
      return locationCcjCount;
    }
    
    /** Sets the value of the 'locationCcjCount' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setLocationCcjCount(java.lang.Integer value) {
      validate(fields()[4], value);
      this.locationCcjCount = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'locationCcjCount' field has been set */
    public boolean hasLocationCcjCount() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'locationCcjCount' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearLocationCcjCount() {
      locationCcjCount = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'locationCcjPercentage' field */
    public java.lang.CharSequence getLocationCcjPercentage() {
      return locationCcjPercentage;
    }
    
    /** Sets the value of the 'locationCcjPercentage' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setLocationCcjPercentage(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.locationCcjPercentage = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'locationCcjPercentage' field has been set */
    public boolean hasLocationCcjPercentage() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'locationCcjPercentage' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearLocationCcjPercentage() {
      locationCcjPercentage = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'locationBusinessLimit' field */
    public java.lang.Integer getLocationBusinessLimit() {
      return locationBusinessLimit;
    }
    
    /** Sets the value of the 'locationBusinessLimit' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setLocationBusinessLimit(java.lang.Integer value) {
      validate(fields()[6], value);
      this.locationBusinessLimit = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'locationBusinessLimit' field has been set */
    public boolean hasLocationBusinessLimit() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'locationBusinessLimit' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearLocationBusinessLimit() {
      locationBusinessLimit = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'ccjIndicator' field */
    public java.lang.Boolean getCcjIndicator() {
      return ccjIndicator;
    }
    
    /** Sets the value of the 'ccjIndicator' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setCcjIndicator(java.lang.Boolean value) {
      validate(fields()[7], value);
      this.ccjIndicator = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'ccjIndicator' field has been set */
    public boolean hasCcjIndicator() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'ccjIndicator' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearCcjIndicator() {
      ccjIndicator = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'ccjDate' field */
    public java.lang.CharSequence getCcjDate() {
      return ccjDate;
    }
    
    /** Sets the value of the 'ccjDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setCcjDate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.ccjDate = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'ccjDate' field has been set */
    public boolean hasCcjDate() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'ccjDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearCcjDate() {
      ccjDate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'gazetteDate' field */
    public java.lang.CharSequence getGazetteDate() {
      return gazetteDate;
    }
    
    /** Sets the value of the 'gazetteDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder setGazetteDate(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.gazetteDate = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'gazetteDate' field has been set */
    public boolean hasGazetteDate() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'gazetteDate' field */
    public com.equifax.fabric.uk.purposing.companies.courtjudgment.Summary.Builder clearGazetteDate() {
      gazetteDate = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public Summary build() {
      try {
        Summary record = new Summary();
        record.currentCcjCount = fieldSetFlags()[0] ? this.currentCcjCount : (java.lang.Integer) defaultValue(fields()[0]);
        record.latestCcjDate = fieldSetFlags()[1] ? this.latestCcjDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.satisfiedCcjCount = fieldSetFlags()[2] ? this.satisfiedCcjCount : (java.lang.Integer) defaultValue(fields()[2]);
        record.latestSatisfiedCcjDate = fieldSetFlags()[3] ? this.latestSatisfiedCcjDate : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.locationCcjCount = fieldSetFlags()[4] ? this.locationCcjCount : (java.lang.Integer) defaultValue(fields()[4]);
        record.locationCcjPercentage = fieldSetFlags()[5] ? this.locationCcjPercentage : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.locationBusinessLimit = fieldSetFlags()[6] ? this.locationBusinessLimit : (java.lang.Integer) defaultValue(fields()[6]);
        record.ccjIndicator = fieldSetFlags()[7] ? this.ccjIndicator : (java.lang.Boolean) defaultValue(fields()[7]);
        record.ccjDate = fieldSetFlags()[8] ? this.ccjDate : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.gazetteDate = fieldSetFlags()[9] ? this.gazetteDate : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
