/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class otherFields extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"otherFields\",\"namespace\":\"com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other\",\"fields\":[{\"name\":\"shortTermUnspecifiedSecured\",\"type\":[\"null\",\"string\"],\"doc\":\"Other - Short Term Unspecified Secured\",\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"longTermUnspecifiedSecured\",\"type\":[\"null\",\"string\"],\"doc\":\"Other - Long Term Unspecified Secured\",\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"unknownPeriodSecured\",\"type\":[\"null\",\"string\"],\"doc\":\"Other - Unknown Period Secured\",\"default\":null,\"dataClassification\":\"3\"},{\"name\":\"unspecifiedBankLoans\",\"type\":[\"null\",\"string\"],\"doc\":\"Other - Unspecified Bank Loans\",\"default\":null,\"dataClassification\":\"3\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Other - Short Term Unspecified Secured */
  @Deprecated public java.lang.CharSequence shortTermUnspecifiedSecured;
  /** Other - Long Term Unspecified Secured */
  @Deprecated public java.lang.CharSequence longTermUnspecifiedSecured;
  /** Other - Unknown Period Secured */
  @Deprecated public java.lang.CharSequence unknownPeriodSecured;
  /** Other - Unspecified Bank Loans */
  @Deprecated public java.lang.CharSequence unspecifiedBankLoans;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public otherFields() {}

  /**
   * All-args constructor.
   */
  public otherFields(java.lang.CharSequence shortTermUnspecifiedSecured, java.lang.CharSequence longTermUnspecifiedSecured, java.lang.CharSequence unknownPeriodSecured, java.lang.CharSequence unspecifiedBankLoans) {
    this.shortTermUnspecifiedSecured = shortTermUnspecifiedSecured;
    this.longTermUnspecifiedSecured = longTermUnspecifiedSecured;
    this.unknownPeriodSecured = unknownPeriodSecured;
    this.unspecifiedBankLoans = unspecifiedBankLoans;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shortTermUnspecifiedSecured;
    case 1: return longTermUnspecifiedSecured;
    case 2: return unknownPeriodSecured;
    case 3: return unspecifiedBankLoans;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shortTermUnspecifiedSecured = (java.lang.CharSequence)value$; break;
    case 1: longTermUnspecifiedSecured = (java.lang.CharSequence)value$; break;
    case 2: unknownPeriodSecured = (java.lang.CharSequence)value$; break;
    case 3: unspecifiedBankLoans = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'shortTermUnspecifiedSecured' field.
   * Other - Short Term Unspecified Secured   */
  public java.lang.CharSequence getShortTermUnspecifiedSecured() {
    return shortTermUnspecifiedSecured;
  }

  /**
   * Sets the value of the 'shortTermUnspecifiedSecured' field.
   * Other - Short Term Unspecified Secured   * @param value the value to set.
   */
  public void setShortTermUnspecifiedSecured(java.lang.CharSequence value) {
    this.shortTermUnspecifiedSecured = value;
  }

  /**
   * Gets the value of the 'longTermUnspecifiedSecured' field.
   * Other - Long Term Unspecified Secured   */
  public java.lang.CharSequence getLongTermUnspecifiedSecured() {
    return longTermUnspecifiedSecured;
  }

  /**
   * Sets the value of the 'longTermUnspecifiedSecured' field.
   * Other - Long Term Unspecified Secured   * @param value the value to set.
   */
  public void setLongTermUnspecifiedSecured(java.lang.CharSequence value) {
    this.longTermUnspecifiedSecured = value;
  }

  /**
   * Gets the value of the 'unknownPeriodSecured' field.
   * Other - Unknown Period Secured   */
  public java.lang.CharSequence getUnknownPeriodSecured() {
    return unknownPeriodSecured;
  }

  /**
   * Sets the value of the 'unknownPeriodSecured' field.
   * Other - Unknown Period Secured   * @param value the value to set.
   */
  public void setUnknownPeriodSecured(java.lang.CharSequence value) {
    this.unknownPeriodSecured = value;
  }

  /**
   * Gets the value of the 'unspecifiedBankLoans' field.
   * Other - Unspecified Bank Loans   */
  public java.lang.CharSequence getUnspecifiedBankLoans() {
    return unspecifiedBankLoans;
  }

  /**
   * Sets the value of the 'unspecifiedBankLoans' field.
   * Other - Unspecified Bank Loans   * @param value the value to set.
   */
  public void setUnspecifiedBankLoans(java.lang.CharSequence value) {
    this.unspecifiedBankLoans = value;
  }

  /** Creates a new otherFields RecordBuilder */
  public static com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder newBuilder() {
    return new com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder();
  }
  
  /** Creates a new otherFields RecordBuilder by copying an existing Builder */
  public static com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder newBuilder(com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder other) {
    return new com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder(other);
  }
  
  /** Creates a new otherFields RecordBuilder by copying an existing otherFields instance */
  public static com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder newBuilder(com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields other) {
    return new com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder(other);
  }
  
  /**
   * RecordBuilder for otherFields instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<otherFields>
    implements org.apache.avro.data.RecordBuilder<otherFields> {

    private java.lang.CharSequence shortTermUnspecifiedSecured;
    private java.lang.CharSequence longTermUnspecifiedSecured;
    private java.lang.CharSequence unknownPeriodSecured;
    private java.lang.CharSequence unspecifiedBankLoans;

    /** Creates a new Builder */
    private Builder() {
      super(com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shortTermUnspecifiedSecured)) {
        this.shortTermUnspecifiedSecured = data().deepCopy(fields()[0].schema(), other.shortTermUnspecifiedSecured);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.longTermUnspecifiedSecured)) {
        this.longTermUnspecifiedSecured = data().deepCopy(fields()[1].schema(), other.longTermUnspecifiedSecured);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unknownPeriodSecured)) {
        this.unknownPeriodSecured = data().deepCopy(fields()[2].schema(), other.unknownPeriodSecured);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unspecifiedBankLoans)) {
        this.unspecifiedBankLoans = data().deepCopy(fields()[3].schema(), other.unspecifiedBankLoans);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing otherFields instance */
    private Builder(com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields other) {
            super(com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.SCHEMA$);
      if (isValidValue(fields()[0], other.shortTermUnspecifiedSecured)) {
        this.shortTermUnspecifiedSecured = data().deepCopy(fields()[0].schema(), other.shortTermUnspecifiedSecured);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.longTermUnspecifiedSecured)) {
        this.longTermUnspecifiedSecured = data().deepCopy(fields()[1].schema(), other.longTermUnspecifiedSecured);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unknownPeriodSecured)) {
        this.unknownPeriodSecured = data().deepCopy(fields()[2].schema(), other.unknownPeriodSecured);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unspecifiedBankLoans)) {
        this.unspecifiedBankLoans = data().deepCopy(fields()[3].schema(), other.unspecifiedBankLoans);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'shortTermUnspecifiedSecured' field */
    public java.lang.CharSequence getShortTermUnspecifiedSecured() {
      return shortTermUnspecifiedSecured;
    }
    
    /** Sets the value of the 'shortTermUnspecifiedSecured' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder setShortTermUnspecifiedSecured(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.shortTermUnspecifiedSecured = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'shortTermUnspecifiedSecured' field has been set */
    public boolean hasShortTermUnspecifiedSecured() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'shortTermUnspecifiedSecured' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder clearShortTermUnspecifiedSecured() {
      shortTermUnspecifiedSecured = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'longTermUnspecifiedSecured' field */
    public java.lang.CharSequence getLongTermUnspecifiedSecured() {
      return longTermUnspecifiedSecured;
    }
    
    /** Sets the value of the 'longTermUnspecifiedSecured' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder setLongTermUnspecifiedSecured(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.longTermUnspecifiedSecured = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'longTermUnspecifiedSecured' field has been set */
    public boolean hasLongTermUnspecifiedSecured() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'longTermUnspecifiedSecured' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder clearLongTermUnspecifiedSecured() {
      longTermUnspecifiedSecured = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'unknownPeriodSecured' field */
    public java.lang.CharSequence getUnknownPeriodSecured() {
      return unknownPeriodSecured;
    }
    
    /** Sets the value of the 'unknownPeriodSecured' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder setUnknownPeriodSecured(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.unknownPeriodSecured = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'unknownPeriodSecured' field has been set */
    public boolean hasUnknownPeriodSecured() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'unknownPeriodSecured' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder clearUnknownPeriodSecured() {
      unknownPeriodSecured = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'unspecifiedBankLoans' field */
    public java.lang.CharSequence getUnspecifiedBankLoans() {
      return unspecifiedBankLoans;
    }
    
    /** Sets the value of the 'unspecifiedBankLoans' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder setUnspecifiedBankLoans(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.unspecifiedBankLoans = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'unspecifiedBankLoans' field has been set */
    public boolean hasUnspecifiedBankLoans() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'unspecifiedBankLoans' field */
    public com.equifax.fabric.uk.ingestion.companyfinancialstatement.rawfields.data.other.otherFields.Builder clearUnspecifiedBankLoans() {
      unspecifiedBankLoans = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public otherFields build() {
      try {
        otherFields record = new otherFields();
        record.shortTermUnspecifiedSecured = fieldSetFlags()[0] ? this.shortTermUnspecifiedSecured : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.longTermUnspecifiedSecured = fieldSetFlags()[1] ? this.longTermUnspecifiedSecured : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.unknownPeriodSecured = fieldSetFlags()[2] ? this.unknownPeriodSecured : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.unspecifiedBankLoans = fieldSetFlags()[3] ? this.unspecifiedBankLoans : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
